GET http://localhost:9090/medium/users

###
GET http://localhost:8080/medium/users/10012

###
POST http://localhost:9090/medium/users
content-type: application/json

{
    "birthDate": {
        "year": 1987,
        "month": 02,
        "day": 06
    },
    "name": "Rimas"
}

###
POST http://localhost:9090/medium/users/3/posts
content-type: application/json

{
    "description": "I wang to learn GCP"
}

###
DELETE http://localhost:9090/medium/users/1